package:
  name: multinest
  version: "3.10"

source:
  git_url: https://github.com/JohannesBuchner/MultiNest

build:
   number: 0
   skip: true  # [win]

requirements:

  build:
    - toolchain
    - cmake
    - lapack
    - openblas
    - gcc  # [osx]
    - libgfortran  # [linux]
    - mpich

  run:
    - lapack
    - openblas
    - mpich
    - libgfortran

test:
  commands:
    - bash -c "cd ${PREFIX}/bin ; mkdir chains ; gaussian"
    - test -f ${PREFIX}/lib/libmultinest.so  # [linux]
    
    - test -f ${PREFIX}/lib/libmultinest.dylib  # [osx]
    
    - test -f ${PREFIX}/include/multinest.h
    - python -c "import pymultinest"
    
    - conda inspect linkages --show-files -p $PREFIX multinest  # [not win]
    - conda inspect objects -p $PREFIX multinest  # [osx]
  
  requires:
    - pymultinest


about:
  home: https://github.com/JohannesBuchner/MultiNest
  license: custom
  license_file: license.pdf
  summary: MultiNest is a Bayesian inference tool which calculates the evidence and explores the parameter space which may contain multiple posterior modes and pronounced (curving) degeneracies in moderately high dimensions.

extra:
  recipe-maintainers:
    - giacomov
    - farhanferoz
