{% set version = "3.10" %}

package:
  name: multinest
  version: {{ version }}

source:
  url: https://github.com/JohannesBuchner/MultiNest/archive/v{{ version }}.tar.gz
  sha256: 8900588ddb4ece8ec09bb1cc4df80e3f02157b278176635d9ef9cdc1992559ce

build:
   number: 8
   skip: true  # [win]

requirements:

  build:
    - cmake <4
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - mpich
  run:
    - mpich

test:
  commands:
    - bash -c "cd ${PREFIX}/bin ; mkdir chains ; gaussian"
    - test -f ${PREFIX}/lib/libmultinest.so  # [linux]

    - test -f ${PREFIX}/lib/libmultinest.dylib  # [osx]

    - test -f ${PREFIX}/include/multinest.h
    - python -c "import pymultinest"


  requires:
    - pymultinest


about:
  home: https://github.com/JohannesBuchner/MultiNest
  license: custom
  license_file: LICENSE
  summary: MultiNest is a Bayesian inference tool which calculates the evidence and explores the parameter space which may contain multiple posterior modes and pronounced (curving) degeneracies in moderately high dimensions.

extra:
  recipe-maintainers:
    - giacomov
    - farhanferoz
